# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser/user.proto\x12\x04user\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x11\n\x0fGetUsersRequest\"=\n\x10GetUsersResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x18\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\n.user.User2H\n\x0bUserService\x12\x39\n\x08GetUsers\x12\x15.user.GetUsersRequest\x1a\x16.user.GetUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=25
  _globals['_USER']._serialized_end=57
  _globals['_GETUSERSREQUEST']._serialized_start=59
  _globals['_GETUSERSREQUEST']._serialized_end=76
  _globals['_GETUSERSRESPONSE']._serialized_start=78
  _globals['_GETUSERSRESPONSE']._serialized_end=139
  _globals['_USERSERVICE']._serialized_start=141
  _globals['_USERSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
